name: Backend CI

on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: briitzacr.azurecr.io
      RESOURCE_GROUP: briitz_rg
      CLUSTER_NAME: briitzaks
      IMAGE_ID: backend

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      

    - name: 'Login to Azure using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 


    - name: ACR login via Azure CLI (OIDC)
      run: az acr login --name briitzacr


    - name: Set AKS Context
      run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing


    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice:latest -f microservice/


    - name: Push Docker image
      run: |
          docker push $REGISTRY/:latest


    - name: Deploy to AKS
      run: |
          kubectl apply -f ./backend/k8s/dev/deployment.yaml
          kubectl apply -f ./backend/k8s/dev/service.yaml  